add_newline = false

continuation_prompt = '[ │ ](fg:mauve)'

format = """
$status\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$line_break\
$character\
"""

[fill]
symbol = "─"
style = "fg:mauve"

[character]
success_symbol = "[  ](fg:green)"
error_symbol = "[  ](fg:red)"
vimcmd_symbol = "[  ](fg:blue)"

[status]
format = "[─](fg:mauve)[](fg:red)[](fg:mantle bg:red)[](fg:red bg:surface0)[ $status](bg:surface0)[](fg:surface0)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[─](fg:mauve)[](fg:red)[](fg:mantle bg:red)[](fg:red bg:surface0)[ $pipestatus](bg:surface0)[](fg:surface0)"
disabled = false

[directory]
format = "[─](fg:mauve)[](fg:mauve)[ ](fg:mantle bg:mauve)[](fg:mauve bg:surface0)[ $path](bg:surface0)[](fg:surface0)"
truncate_to_repo = true
truncation_length = 0

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Repos" = "󰲋 "
"dotfiles" = " "
"github.com" = " "

[git_branch]
format = "[─](fg:mauve)[](fg:peach)[](fg:mantle bg:peach)[](fg:peach bg:surface0)[ $branch](bg:surface0)"

[git_status]
format = "[](fg:surface0 bg:peach)[$all_status$ahead_behind](fg:mantle bg:peach)[](fg:peach)"

[cmd_duration]
format = "[─](fg:mauve)[](fg:green)[󱐋](fg:mantle bg:green)[](fg:green bg:surface0)[ $duration](bg:surface0)[](fg:surface0)"
min_time = 0

[custom.pretty_pwd]
disabled = false
when = "command -v pretty_pwd >/dev/null"
command = "pretty_pwd"
description = "Pretty PWD"
shell = "zsh"
# style = "fg:base bg:red"
style = "fg:text bg:surface1"
format = "[ $output ]($style)"

[palettes.catppuccin_latte]
# 抹茶ラテ風の調整（nvim設定ベース - 最新版）
text = "#1f2b1f"
subtext1 = "#2d3a2d"
subtext0 = "#3c4b3c"
overlay2 = "#556655"
overlay1 = "#748974"
overlay0 = "#8fa58f"
surface2 = "#a9bea9"
surface1 = "#c3d7c3"
surface0 = "#d6e6d6"
crust = "#e1eee1"     # 少し緑が強くなるよう補正
mantle = "#eaf6ea"    # ミルク寄りの明るいグリーン
base = "#edf9ed"      # やや緑がかった優しい背景

# アクセントカラー（濃く、しっかり主張）
rosewater = "#e64553" # しっかり赤みがある苺ピンク
flamingo = "#d83a5e"  # ベリー系レッド
pink = "#d33893"      # ビビッドフューシャピンク
mauve = "#894ec0"     # 濃いスミレ紫
red = "#c72039"       # 漆赤（うるしあか）風
maroon = "#a32442"    # 黒蜜寄りの深紅
peach = "#dd5e00"     # 焼きピーチ系オレンジ
yellow = "#c39b00"    # 金茶・からし色
green = "#4ca748"     # 抹茶をより濃く！ほうじ茶寄りも感じる
teal = "#268e87"      # 深い抹茶ミント
blue = "#2a7fff"      # 抹茶に映える鮮やかブルー
sky = "#1ea8c8"       # 透き通る深めの青空
sapphire = "#0079a6"  # くっきりした藍色
lavender = "#6b6cd9"  # 濃ラベンダーで安定感ある紫

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_matcha]
rosewater = "#e8d5c4"
flamingo = "#d4c5a9"
pink = "#c9b897"
mauve = "#a8b894"
red = "#b85450"
maroon = "#a67c6a"
peach = "#c49963"
yellow = "#d4c985"
green = "#7ba05b"
teal = "#6b9080"
sky = "#5a8f7b"
sapphire = "#6a8caf"
blue = "#708090"
lavender = "#8a9ba8"
text = "#d4e6d4"
subtext1 = "#bdd2bd"
subtext0 = "#a6bea6"
overlay2 = "#8fa68f"
overlay1 = "#788e78"
overlay0 = "#617661"
surface2 = "#4a5e4a"
surface1 = "#384638"
surface0 = "#2a342a"
base = "#1e2b1e"
mantle = "#182118"
crust = "#0f150f"
