# palette = "catppuccin_mocha"
palette = "catppuccin_frappe"


format = """
$character\
$directory\
[](fg:surface1 bg:peach)\
$git_branch\
$git_status\
[](fg:peach)\
$fill\
[](fg:blue)\
$time\
[](fg:blue)
[ 󰐊 ](fg:mauve)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

continuation_prompt = '[ | ](fg:mauve)'

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol        = "[](bg:base fg:green)[ I ](fg:base bg:green bold)[](bg:surface0 fg:green)"
error_symbol          = "[](bg:base fg:red)[ I ](fg:base bg:red bold)[](bg:surface1 fg:red)"
vimcmd_symbol         = "[](bg:base fg:blue)[ N ](fg:base bg:blue bold)[](bg:surface1 fg:blue)"
format = "[$symbol]($style)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:base bg:mauve"
style_root = "fg:base bg:mauve"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:base bg:mauve"
disabled = false # Disabled by default

[os.symbols]
Macos = " "

[directory]
style = "fg:text bg:surface1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:text bg:surface1"
format = '[ $context ]($style)'

[elixir]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:base bg:peach"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:base bg:peach"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[buf]
symbol = "󰴗 "
style = "fg:base bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:base bg:blue"
format = '[ ♥ $time ]($style)'

[custom.pretty_pwd]
disabled = false
when = "command -v pretty_pwd >/dev/null"
command = "pretty_pwd"
description = "Pretty PWD"
shell = "zsh"
style = "fg:base bg:red"
format = "[ $output ]($style)"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
