FROM ubuntu

ADD https://raw.githubusercontent.com/cry999/my-configs/master/.zshrc /root/.zshrc

RUN apt-get update -y
RUN apt-get install -y \
	git \
	zsh \
	language-pack-ja \
	locales
RUN locale-gen

ENV TERM=xterm-256color

ENTRYPOINT [ "zsh" ]
