#!/usr/bin/env bash
#
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
# ITEMS_DIR="$CONFIG_DIR/items"

FONT="SF Pro"
THEME="macchiato"

LOG_FILE="/tmp/sketchybar.log"

. "$CONFIG_DIR/colors.sh"
. "$CONFIG_DIR/constants.sh"

__logging() {
  echo "sketchybarrc: $@" >> $LOG_FILE
}

sketchybar --add event aerospace_workspace_change

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=45
  topmost=window
  color=0x00000000
)
sketchybar --bar "${bar[@]}"

PADDING=5
ICON_FONT="sketchybar-app-font:Regular:16.0"

left_container=(
  background.color=${SURFACE2/0xff/0x88}
  background.border_color=$TEXT
  background.border_width=$BORDER_WIDTH
  background.corner_radius=$BORDER_RADIUS
  background.height=$BACKGROUND_HEIGHT
)

# most left icon
apple_icon=(
  icon=""
  icon.color=$TEXT
  icon.font="JetBrainsMono Nerd Font:Bold:16.0"
  icon.padding_left=20
  icon.padding_right=20
  background.color=$MAUVE
  background.border_width=$BORDER_WIDTH
  background.border_color=$TRANSPARENT
  background.padding_left=$((BORDER_WIDTH / 2))
  background.padding_right=$((BORDER_WIDTH / 2))
  background.height=$((BACKGROUND_HEIGHT-BORDER_WIDTH/2))
  background.corner_radius=$BORDER_RADIUS
)

sketchybar \
  --add item apple left \
  --set apple  "${apple_icon[@]}"

focused_workspace_id=$(aerospace list-workspaces --focused --format '%{workspace}')
__logging focused_workspace_id: $focused_workspace_id
AEROSPACE_FOCUSED_WORKSPACE=$focused_workspace_id SENDER=init $PLUGIN_DIR/space.sh

spaces=(
  margin=20
  background.corner_radius=$BORDER_RADIUS
  background.height=$BACKGROUND_HEIGHT
  script="$PLUGIN_DIR/space.sh"
)

sketchybar \
  --add bracket spaces '/space\..*/' \
  --set spaces "${spaces[@]}"

sketchybar \
  --add bracket left_container apple spaces \
  --set left_container "${left_container[@]}"

sketchybar \
  --add bracket spaces2 '/space\..*/' \
  --set spaces2 "${spaces[@]}" \
  --subscribe spaces2 aerospace_workspace_change space_windows_change

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# . $ITEMS_DIR/front_app.sh

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

# sketchybar --add item clock right \
#            --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
#            --add item volume right \
#            --set volume script="$PLUGIN_DIR/volume.sh" \
#            --subscribe volume volume_change \
#            --add item battery right \
#            --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
#            --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --hotload on
sketchybar --update
