palette = "catppuccin_frappe"

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol        = "[▎  ](green)"
error_symbol          = "[▎  ](red  )"
vimcmd_symbol         = "[▎  ](blue )"

[directory]
truncation_length = 4
# Catppuccin 'lavender'
format = "[  ](inverted lavender)[ $path ](lavender)"

[git_branch]
format="([  ](inverted bold peach)[ $branch(:$remote_branch) ](peach))"

# [git_commit]
# format = "([ 󰓹 $hash$tag ](inverted peach))"
# tag_disabled = false

[git_metrics]
disabled = false
format = "([ $added ](green))([ $deleted ](red))"

[git_status]
format = "([$all_status$ahead_behind](peach))"
conflicted = ""
modified = " "
untracked = "★ "
staged = "✓"
renamed = "➜"
deleted = "✗"

[aws]
format = "[ 󰸏 ](inverted yellow)[ $profile ](yellow)"

[battery]
disabled = true

[container]
format = "[▎   ](bold sky)"
style = "bold sky"

[golang]
format = "[  ](inverted bold sky)[( $version )](sky)"

[gradle]
format = "[  ](inverted bold text)[( $version )](text)"

[java]
format = "[ 󰬷 ](inverted bold flamingo)[( $version )](flamingo)"

[lua]
format = "[ 󰢱 ](inverted bold yellow)[( $version )](yellow)"

[nodejs]
format = "[ 󰎙 ](inverted bold green)[( $version )](green)"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
