palette = "catppuccin_frappe"

format  = """
$aws$directory$golang$gradle$java$lua$nodejs$package$python$rust$swift$terraform$fill\
$git_branch$git_commit$git_metrics$git_status
$character
"""

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol        = "[  ](inverted green)[ ➜ ](green)"
error_symbol          = "[  ](inverted red  )[ ➜ ](red  )"
vimcmd_symbol         = "[  ](inverted blue )[ ➜ ](blue )"

[fill]
symbol = "┄"

[directory]
truncation_length = 4
# Catppuccin 'lavender'
format = "[  ](inverted lavender)[ $path ](lavender bg:surface1)"

[git_branch]
format="([  ](inverted bold peach)[ $branch(:$remote_branch) ](peach bg:surface1))"

[git_commit]
format = "([ $hash $tag ](peach bg:surface1))"
tag_symbol = "󰓹 "
only_detached = false
tag_disabled = false
disabled = false

[git_metrics]
disabled = false
format = "([ $added ](green bg:surface1))([ $deleted ](red bg:surface1))"

[git_status]
format = "$all_status$ahead_behind"
conflicted = "[ ](red bg:surface1)"
modified = "[ ](mauve bg:surface1)"
untracked = "[★ ] (yellow bg:surface1)"
stashed = "[ ](teal bg:surface1)"
staged = "[✓ ](green bg:surface1)"
renamed = "[➜ ](mauve bg:surface1)"
deleted = "[✗ ](red bg:surface1)"

[aws]
format = "[ 󰸏 ](inverted yellow)[ $profile ](yellow bg:surface1)"

[battery]
disabled = true

[container]
format = "[  ](inverted sky bg:surface1)"

[golang]
format = "[  ](inverted bold sky)[( $version )](sky bg:surface1)"

[gradle]
format = "[  ](inverted bold text)[( $version )](text bg:surface1)"

[java]
format = "[ 󰬷 ](inverted bold flamingo)[( $version )](flamingo bg:surface1)"

[lua]
format = "[ 󰢱 ](inverted bold yellow)[( $version )](yellow bg:surface1)"

[nodejs]
format = "[ 󰎙 ](inverted bold green)[( $version )](green bg:surface1)"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
