#!/usr/bin/env zsh

if which brew >/dev/null 2>&1; then
	echo "brew already exists"
else
	echo "install home brew"
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi
export PATH=/opt/homebrew/bin:$PATH
brew -v

# brew bundle
