#!/usr/bin/env sh

# global settings
yabai -m config                      \
  debug_output          on           \
  external_bar          main:10:10   \
  menubar_opacity       0.5          \
  mouse_follows_focus   on           \
  focus_follows_mouse   autofocus    \
  window_placement      second_child \
  window_shadow         off          \
  window_opacity        off          \
  insert_feedback_color 0x0000ff     \
  split_type            auto         \
  mouse_modifier        alt          \
  mouse_action1         move         \
  mouse_action2         resize       \
  mouse_drop_action     swap

# space settings
yabai -m config \
  layout         bsp \
  top_padding    10  \
  bottom_padding 10  \
  left_padding   10  \
  right_padding  10  \
  window_gap     10  \
  auto_balance   on
